# imagen base
FROM python:3.7.0-alpine

#configurando directorio de trabajo
WORKDIR /usr/src/app

#copiando e instalando paquetes de requirements.txt
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

#copiando app
COPY . /usr/src/app

#ejecutando el servidor
CMD python manage.py run -h 0.0.0.0
